import Head from 'next/head'
import { Hero } from '../components/Hero/Hero'
import { SimpleLayout } from '../layouts/SimpleLayout/SimpleLayout'
import { aboutData } from '../data/about';

export default function Home() {
  return (
    <SimpleLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero userLinks={aboutData.links} />
    </SimpleLayout>
  )
}
