import Head from 'next/head'
import { SimpleLayout } from '../layouts/SimpleLayout/SimpleLayout'

export default function Home() {
  return (
    <SimpleLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </SimpleLayout>
  )
}
