import Head from 'next/head';
import { MainLayout } from '../layouts/MainLayout/MainLayout';
import { TextWithBack } from '../components/TextWIthBack/TextWithBack';
import { i18n } from '../i18n/i18n';
import { RepoStructure } from '../features/projects';
import { ProjectsList } from '../components/ProjectsList/ProjectsList';

type ProjectsProps = {
    projects: RepoStructure[],
}

export default function Projects({ projects }: ProjectsProps) {
    return (
        <MainLayout>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TextWithBack>{i18n.t('projects.title')}</TextWithBack>
            <ProjectsList projects={projects} />
        </MainLayout>
    );
}
